export default [
  {
    id: 1,
    name: "appetiser",
    desc: "panko apple. sriracha. coriander",
    imgSrc: "appetiser.png",
    price: 10,
  },
  {
    id: 2,
    name: "appetistickymisocornser",
    desc: "corn on the cob roundels. sticky miso sauce. red chilli. sesame seeds",
    imgSrc: "stickymisocorn.png",
    price: 14,
  },
  {
    id: 3,
    name: "porkribs",
    desc: "korean barbecue sauce. mixed sesame seeds",
    imgSrc: "porkribs.png",
    price: 150,
  },
  {
    id: 4,
    name: "ebikatsu",
    desc: "prawns in crispy panko breadcrumbs. coriander. fresh lime. chilli sauce",
    imgSrc: "ebikatsu.png",
    price: 125,
  },
  {
    id: 5,
    name: "edamame",
    desc: "beans with salt. pop them out of their pod + enjoy salt",
    imgSrc: "edamame.png",
    price: 13,
  },
  {
    id: 6,
    name: "chillisquid",
    desc: "crispy fried squid. shichimi. spicy vinegar sauce. coriander",
    imgSrc: "chillisquid.png",
    price: 31,
  },
  {
    id: 7,
    name: "cheesetacos",
    desc: "Juicy chicken in original breading, cheese and cheese sauce wrapped in a hot tortilla",
    imgSrc: "cheese-tacos.png",
    price: 25,
  },
  {
    id: 8,
    name: "bitessalsa",
    desc: "Juicy spicy pieces of chicken in crispy breading with salsa sauce",
    imgSrc: "bites-salsa.png",
    price: 55,
  },
  {
    id: 9,
    name: "bucketduet",
    desc: "2 legs, 4 sharp wings, 4 original strips and medium fries.",
    imgSrc: "bucketduet.png",
    price: 19,
  },
  {
    id: 10,
    name: "sushi",
    desc: "14 roll, 3 gragon, 31 chipes",
    imgSrc: "sushi.jpg",
    price: 37,
  },
];
